<a href="https://colab.research.google.com/github/Batovs/MAP2110-2021-Modelagem-Matematica/blob/main/Projeto%205/Ordena%C3%A7%C3%A3o%20de%20P%C3%A1ginas%20do%20Google.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[0, 0, 0, 0, 0, 0, 0, 1/2],
             [1/2, 0, 0, 0, 0, 0, 0, 0],
             [1/2, 1/2, 0, 0, 0, 0, 0, 1/2],
             [0, 1/2, 0, 0, 0, 0, 0, 0],
             [0, 0, 0, 1/2, 0, 0, 0, 0],
             [0, 0, 1/2, 1/2, 1, 0, 0, 0],
             [0, 0, 1/2, 0, 0, 1, 0, 0],
             [0, 0, 0, 0, 0, 0, 1, 0]]              
              )
print(A)

[[0.  0.  0.  0.  0.  0.  0.  0.5]
 [0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.5 0.  0.  0.  0.  0.  0.5]
 [0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 1.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]]


In [ ]:
n = A.shape[1]
S = np.full((n,n),(1/n))
m = 0.15

In [ ]:
n

8

In [ ]:
S

array([[0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]])

In [ ]:
M = (1-m)*A + m*S
print(M)

[[0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.44375]
 [0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875]
 [0.44375 0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.44375]
 [0.01875 0.44375 0.01875 0.01875 0.01875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.44375 0.01875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.44375 0.44375 0.86875 0.01875 0.01875 0.01875]
 [0.01875 0.01875 0.44375 0.01875 0.01875 0.86875 0.01875 0.01875]
 [0.01875 0.01875 0.01875 0.01875 0.01875 0.01875 0.86875 0.01875]]


In [ ]:
def calculo_c(M):
  #minimo de cada coluna
  min_col = np.amin(M, axis=1)
  c = max(abs(1-2*min_col))
  return c


In [ ]:
def MetodoPotencias(M,x0,k=50):
  x1 = M @ x0
  for i in range(k-1):
    x1 = M @ x1
  return x1

In [ ]:
def OrdenaPaginas(A, x0, m=0.15, erro=1e-5):
  n = A.shape[1] #matriz de ligação NxN
  S = np.full((n,n),(1/n))
  M = (1-m)*A + m*S
  e = erro + 1 #erro inicial para entrar no loop
  cnt = 0 #contador inicial
  c = calculo_c(M)
  xk_1 = x0 

  while e >= erro:
    xk = M @ xk_1
    e = (c/(1-c))*np.linalg.norm(xk - xk_1)
    xk_1 = xk 
    cnt += 1
  
  print(f'c = {c}')
  print(f'Vetor dos pesos normalizado:\n{xk}\nApós {cnt} iterações ', end='')
  print(f'com erro menor que {erro}')


In [ ]:
n = A.shape[1]
x0 = np.full((n,1),(1/n))
OrdenaPaginas(A, x0, m=0.15, erro=1e-5)

c = 0.9625
Vetor dos pesos normalizado:
[[0.10564275]
 [0.06364814]
 [0.17759131]
 [0.04580041]
 [0.03821521]
 [0.14617444]
 [0.21847447]
 [0.20445326]]
Após 26 iterações com erro menor que 1e-05


Resolução Intro

In [ ]:
#Resolução Intro
A_intro = np.array([[0, 0, 1, 1/2],
                    [1/3, 0, 0, 0],
                    [1/3, 1/2, 0, 1/2],
                    [1/3, 1/2, 0, 0]])
n = A_intro.shape[1]
x0 = np.full((n,1),(1/n))
MetodoPotencias(A_intro, x0).round(3)

array([[0.387],
       [0.129],
       [0.29 ],
       [0.194]])

Exemplos livro Anton

In [ ]:
A = np.array([[0, 0, 1, 1],
              [1, 0, 0, 0], 
              [1, 0, 0, 1], 
              [1, 1, 1, 0]])
h0 = []
for i in range (A.shape[1]):
  h0.append(A[i].sum())
h0 = np.array(h0)
h0 = np.atleast_2d(h0).T
a0 = []
for i in range (A.shape[1]):
  a0.append(A.T[i].sum())
a0 = np.array(a0)
a0 = np.atleast_2d(a0).T

In [ ]:
Aa0 = A @ a0
Aa0

array([[4],
       [3],
       [5],
       [6]])

In [ ]:
h1 = Aa0/np.linalg.norm(Aa0)
h1

array([[0.43133109],
       [0.32349832],
       [0.53916387],
       [0.64699664]])

In [ ]:
a1 = A.T @ h1/np.linalg.norm(A.T @ h1)
a1

array([[0.68889496],
       [0.2952407 ],
       [0.49206783],
       [0.44286105]])

In [ ]:
def VetorAutoridadeInicial(A):
  a0 = []
  for i in range (A.shape[1]):
    a0.append(A.T[i].sum())
  a0 = np.array(a0)
  a0 = np.atleast_2d(a0).T
  return a0

In [ ]:
def VetorCentroInicial(A):
  h0 = []
  for i in range (A.shape[1]):
    h0.append(A[i].sum())
  h0 = np.array(h0)
  h0 = np.atleast_2d(h0).T
  return h0

In [ ]:
def ak (A, a0, k):
  ak = a0
  for i in range(k):
    ak = ((A.T @ A) @ ak)/np.linalg.norm((A.T @ A) @ ak)
  return ak


In [ ]:
def hk (A, a0, k):
  h1 = A @ a0/np.linalg.norm(A @ a0) #Vetor inicial h0
  if k == 1:
    return h1
  hk = h1 #Valor de h para 
  for i in range(k-1):
    hk = ((A @ A.T) @ hk)/np.linalg.norm((A @ A.T) @ hk)
  return hk

In [ ]:
a0 = VetorAutoridadeInicial(A)
hk(A, a0, 2)


array([[0.42634775],
       [0.31415098],
       [0.51610518],
       [0.67318066]])

Exemplo 3 Anton

In [ ]:
A_exemplo3 = np.array([[0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
                       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
                       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
                       [0, 1, 1, 1, 1, 0, 0, 1, 0, 1],
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],    
                       ])

In [ ]:
a0_ex3 = VetorAutoridadeInicial(A_exemplo3)
ak(A_exemplo3, a0_ex3, 7)

array([[0.00000000e+00],
       [4.19893150e-01],
       [2.53361889e-01],
       [2.53361889e-01],
       [6.25988070e-01],
       [4.67478485e-04],
       [1.93635758e-04],
       [4.71649099e-01],
       [0.00000000e+00],
       [2.84589274e-01]])

In [ ]:
import numpy as np

In [ ]:
np.linalg.eig([[1,1],[1,2]])

(array([0.38196601, 2.61803399]), array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))