<a href="https://colab.research.google.com/github/Batovs/MAP2110-2021-Modelagem-Matematica/blob/main/Projeto%203/Modelo%20Insumo%20Produto%20de%20Leontief.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matriz de Leontief

A matriz de Leontief (L) é dada por:

$L = (I - C)^{-1}$

Onde I é a matiz identidade de ordem n, e C é a matriz de consumo $n _\mathrm{x} n$

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
def Leontief (C): #Matriz de Leontief, dado a matriz Consumo n x n
  n = len(C)
  I = np.identity(n) #Matriz identidade n x n
  if type(C) == list: C = np.array(C) #Transforma em array se a entrada for lista
  I_C = (I - C)
  L = np.linalg.inv(I_C)#Matriz de Leontief
  return L

In [ ]:
def Producao(C,d): #Cálculo da produção dado a matriz consumo e demanda
  if type(C) == list: C = np.array(C) #Transforma em array se a entrada for lista
  if type(d) == list: d = np.atleast_2d(d).T #Transforma d em matriz coluna se for lista
 
  L = Leontief(C)
  
  #Resolução de sistema linear via Matriz Leontief
  #Encontrar o x, multiplicação de matriz (L*d)
  X = np.dot(L,d)

  return X

In [ ]:
c = np.array([[0.5,0.4,0.2],[.2,.3,.1],[.1,.1,.3]])
d = [50,30,20]

In [ ]:
Producao(c,d)

array([[225.92592593],
       [118.51851852],
       [ 77.77777778]])

In [ ]:
Leontief(c)

array([[2.96296296, 1.85185185, 1.11111111],
       [0.92592593, 2.03703704, 0.55555556],
       [0.55555556, 0.55555556, 1.66666667]])

In [ ]:
def Leontief_2(C,n):
  import numpy as np
  
  N = len (C)  #Tamanho da matriz consumo para criacao da matriz identidade
  I = np.identity(N) #Matriz identidade NxN
  L = I - I
  
  for i in range(n):
    L += np.linalg.matrix_power(C,i) #Soma de potências n vezes
  return L

In [ ]:
Leontief(c)-Leontief_2(c,50)

array([[3.68588465e-06, 3.68588465e-06, 2.38016484e-06],
       [1.84294232e-06, 1.84294232e-06, 1.19008242e-06],
       [1.19008242e-06, 1.19008242e-06, 7.68497284e-07]])

##Tarefa 1
---

Considere  uma  economia  dividida  em  três  setores  —  manufatura,  agrícultura  e  serviços.   Para  cada  unidade  produzida,  a  manufatura  requer 0.10  unidades  de  outras  companhias  do  mesmo  setor,  0.30  unidades  da agricultura e 0.30 unidades de serviços.  Para cada unidade produzida, aagricultura usa 0.20 unidades da sua própria produção, 0.60 unidades da manufatura  e  0.10  unidades  de  serviços.   Para  cada  unidade  produzida,o setor de serviços consome 0.10 unidades dele mesmo, 0.60 unidades da manufatura, mas nenhum produto agrícola.

###(a)

Construa a matriz de consumo para esta economia e determine quais demandas intermediárias são criadas se a agricultura planeja produzir 100 unidades

In [ ]:
consumo1 = [[0.1,0.6,0.6],[0.3,0.2,0],[0.3,0.1,0.1]]
consumo1 = np.array(consumo1)
consumo1

array([[0.1, 0.6, 0.6],
       [0.3, 0.2, 0. ],
       [0.3, 0.1, 0.1]])

In [ ]:
#matriz de consumo para DF, melhor visualização
consumo1_df = pd.DataFrame(consumo1)
dic = { 
        0:'manufatura',
        1:'agricultura',
        2:'serviços'
       } #dicionário para mudar o nome das colunas e linhas
consumo1_df.rename(columns = dic, inplace = True)
consumo1_df.rename(index=dic, inplace=True)
consumo1_df

manufatura  agricultura  serviços
manufatura          0.1          0.6       0.6
agricultura         0.3          0.2       0.0
serviços            0.3          0.1       0.1

In [ ]:
demanda_final = [[0],[100],[0]]
demanda_final = np.array(demanda_final)

def calcula_demanda_intermediaria(C, d, n):
  N = len (C)  #Tamanho da matriz consumo para criacao da matriz identidade
  I = np.identity(N) #Matriz identidade NxN
  soma_potencias = I - I

  for i in range(1, n):
    soma_potencias += np.linalg.matrix_power(C,i)
  demanda_intermediaria = np.dot(soma_potencias,d)

  return demanda_intermediaria

calcula_demanda_intermediaria(consumo1, demanda_final, 50)

array([[185.18503442],
       [ 94.44436252],
       [ 83.33325141]])

### (b)

Obtenha a matriz de Leontief e interprete os seus coeficientes.

In [ ]:
Leontief(consumo1)

array([[2.22222222, 1.85185185, 1.48148148],
       [0.83333333, 1.94444444, 0.55555556],
       [0.83333333, 0.83333333, 1.66666667]])

### (c)

Determine os níveis de produção necessários para satisfazer uma demanda final de 18 unidades para a agricultura, e nenhuma demanda final para os outros setores. Que relaçãoo você observa entre a respostae a matriz de Leontief?

In [ ]:
d_ex1 = [0,18,0]
Producao(consumo1,d_ex1)

array([[33.33333333],
       [35.        ],
       [15.        ]])

In [ ]:
Leontief(consumo1_df)*18

array([[40.        , 33.33333333, 26.66666667],
       [15.        , 35.        , 10.        ],
       [15.        , 15.        , 30.        ]])


##Tarefa 2
---
A matriz de consumo abaixo em dados de insumo-produto da economianorte-americana em 1958, com dados para 81 setores agrupados em 7 grandes setores: (1) produtos domésticos e pessoais não metálicos, (2) produtos metálicos finais (como veículos motorizados), (3) produtos metálicos básicos e mineração, (4) produtos não metálicos básicos e agricultura, (5)energia, (6) serviços e (7) produtos diversos


In [ ]:
#matriz copiada do pdf
matriz = '.1588.0064.0025.0304.0014.0083.1594.0057.2645.0436.0099.0083.0201.3413.0264.1506.3557.0139.0142.0070.0236.3299.0565.0495.3636.0204.0483.0649.0089.0081.0333.0295.3412.0237.0020.1190.0901.0996.1260.1722.2368.3369.0063.0126.0196.0098.0064.0132.0012'
ex2 = []
for i in range(1,50):
  ex2.append(int(matriz.split('.')[i])/10000)
matriz_ex2 = np.array([ex2[:7],ex2[7:14],ex2[14:21],ex2[21:28],ex2[28:35],ex2[35:42],ex2[42:]])
pd.DataFrame(matriz_ex2)

0       1       2       3       4       5       6
0  0.1588  0.0064  0.0025  0.0304  0.0014  0.0083  0.1594
1  0.0057  0.2645  0.0436  0.0099  0.0083  0.0201  0.3413
2  0.0264  0.1506  0.3557  0.0139  0.0142  0.0070  0.0236
3  0.3299  0.0565  0.0495  0.3636  0.0204  0.0483  0.0649
4  0.0089  0.0081  0.0333  0.0295  0.3412  0.0237  0.0020
5  0.1190  0.0901  0.0996  0.1260  0.1722  0.2368  0.3369
6  0.0063  0.0126  0.0196  0.0098  0.0064  0.0132  0.0012

In [ ]:
matriz_ex2_df = pd.DataFrame(matriz_ex2)
dic_2 = {
        0:'domésticos e pessoais não metálicos',
        1:'metálicos finais',
        2:'metálicos básicos e mineração',
        3:' metálicos básicos e mineração',
        4: 'não metálicos básicos e agricultura',
        5: 'energia',
        6: 'serviços',
        7: 'diversos'
        } #dicionário para mudar o nome das colunas e linhas
matriz_ex2_df.rename(columns = dic_2, inplace = True)
matriz_ex2_df.rename(index=dic_2, inplace=True)
matriz_ex2_df

domésticos e pessoais não metálicos  ...  serviços
domésticos e pessoais não metálicos                               0.1588  ...    0.1594
metálicos finais                                                  0.0057  ...    0.3413
metálicos básicos e mineração                                     0.0264  ...    0.0236
 metálicos básicos e mineração                                    0.3299  ...    0.0649
não metálicos básicos e agricultura                               0.0089  ...    0.0020
energia                                                           0.1190  ...    0.3369
serviços                                                          0.0063  ...    0.0012

[7 rows x 7 columns]

In [ ]:
d_ex2_1 = [74000 , 56000 , 10500 , 25000 , 17500 , 196000 , 5000]
Producao(matriz_ex2,d_ex2_1)

array([[ 99575.65339765],
       [ 97703.02286349],
       [ 51230.52316638],
       [131569.92192872],
       [ 49488.49137236],
       [329554.45256999],
       [ 13835.33571501]])

In [ ]:
d_ex2_2 = [99640 , 75548 , 14444 , 33501 , 23527 , 263985 , 6526]
Producao(matriz_ex2,d_ex2_2)

array([[134033.61532755],
       [131686.642968  ],
       [ 69471.69907937],
       [176912.002023  ],
       [ 66595.55670623],
       [443772.90207667],
       [ 18431.17768329]])

##Tarefa 3
---
Na página do IBGE https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9085-matriz-de-insumo-produto.html há informações sobre o resultado de atividades econômicas.  Leia a explicação.  Depois,clique o link ”Downloads” à esquerda na página, acesse as informações do ano de 2015 e baixe a planilha relativa a 12 setores da economia. Nesta planilha, localize a aba que contém a matriz de consumo e calculea matriz de Leontief.  Compare o seu resultado com a matriz de Leontiefque está na planilha.  Interprete alguns coeficientes da matriz de Leontief.


In [ ]:
def Tratamento_excel(nome_arquivo,nome_aba): 
  #Função para tratar o arquivo excel e devolver um DataFrame limpo para ser utilizado
  
  import pandas as pd
  import re
 
  #Tratamento inicial
  df = pd.read_excel(nome_arquivo,sheet_name=nome_aba,header=3).drop(['Unnamed: 0','Unnamed: 1'],axis=1)
  df = df.dropna()
  df = df.reset_index().drop('index',axis=1)

  #tratar o nome das colunas com Regex
  colunas = []#nome das colunas limpo
  for item in  df.columns: #tira o número e o '\n' 
    colunas.append(re.sub('(.*\\n)','',item))

  #Renomear colunas e index
  dic_col = dict(zip(df.columns,colunas)) #dicionário para renomear as colunas
  df.rename(columns = dic_col, inplace = True)
  lendf = len(df)
  dic_index = dict(zip(range(0,lendf),colunas))#dicionário para renomear os index
  df.rename(index=dic_index, inplace=True)
  
  return df

In [ ]:
matriz_consumo = Tratamento_excel('Matriz_de_Insumo_Produto_2015_Nivel_12.xls','14')
matriz_consumo

Agropecuária  ...  Administração, defesa, saúde e educação públicas e seguridade social
Agropecuária                                            0.040534  ...                                           0.001568                   
Indústrias extrativas                                   0.001103  ...                                           0.000294                   
Indústrias de transformação                             0.206423  ...                                           0.025899                   
Eletricidade e gás, água, esgoto e gestão de re...      0.023301  ...                                           0.017256                   
Construção                                              0.000593  ...                                           0.013924                   
Comércio                                                0.059395  ...                                           0.013314                   
Transporte, armazenagem e correio                       0.019994  ...                                           0.011773                   
Informação e comunicação                                0.000202  ...                                           0.017332                   
Atividades financeiras, de seguros e serviços r...      0.015253  ...                                           0.044628                   
Atividades imobiliárias                                 0.000036  ...                                           0.003605                   
Outras atividades de serviços                           0.003692  ...                                           0.078202                   
Administração, defesa, saúde e educação pública...      0.000741  ...                                           0.003469                   

[12 rows x 12 columns]

In [ ]:
matriz_leontif = Leontief(matriz_consumo) #Aplicando a função Leontief na matriz consumo (IBGE 12)
matriz_leontif_df = pd.DataFrame(matriz_leontif)
matriz_leontif_df

0         1         2   ...        9         10        11
0   1.070423  0.020221  0.119541  ...  0.001716  0.016688  0.007821
1   0.017118  1.068457  0.066637  ...  0.001611  0.007045  0.004035
2   0.338342  0.228313  1.475315  ...  0.018839  0.137939  0.067116
3   0.046079  0.028026  0.043750  ...  0.003128  0.032043  0.029659
4   0.002713  0.017114  0.004714  ...  0.003652  0.006547  0.017248
5   0.098931  0.067164  0.139921  ...  0.006476  0.054238  0.027237
6   0.052697  0.122596  0.103238  ...  0.003812  0.037013  0.023483
7   0.008163  0.016810  0.020077  ...  0.004658  0.052660  0.028402
8   0.032711  0.042425  0.044851  ...  0.044830  0.031619  0.058562
9   0.005779  0.008309  0.011106  ...  1.003839  0.023276  0.007795
10  0.043049  0.144534  0.111836  ...  0.016832  1.128525  0.107208
11  0.003040  0.007681  0.006545  ...  0.000804  0.006158  1.004951

[12 rows x 12 columns]

In [ ]:
matriz_leontif_df[matriz_leontif_df<1].max()

0     0.338342
1     0.228313
2     0.139921
3     0.190108
4     0.354864
5     0.125413
6     0.324264
7     0.196537
8     0.145253
9     0.044830
10    0.137939
11    0.107208
dtype: float64

In [ ]:
def Leontief_excel(nome_arquivo,nome_aba):

  matriz_consumo = Tratamento_excel(nome_arquivo,nome_aba)
  matriz_leontif = Leontief(matriz_consumo) #Aplicando a função Leontief na matriz consumo (IBGE)
  matriz_leontif_df = pd.DataFrame(matriz_leontif)

  #Renomear colunas e index  
  lendf = len(matriz_consumo)
  dic_index = dict(zip(range(0,lendf),matriz_consumo.columns))#dicionário para renomear os index e colunas
  matriz_leontif_df.rename(index=dic_index, inplace=True)
  matriz_leontif_df.rename(columns = dic_index, inplace = True)


  return matriz_leontif_df
  

In [ ]:
#Comparando os valores do modelo com o dado no site do IBGE
#aba 14 (consumo), aba 15 (Leontief)
display(round(Leontief_excel('Matriz_de_Insumo_Produto_2015_Nivel_12.xls','14')) == round(Tratamento_excel('Matriz_de_Insumo_Produto_2015_Nivel_12.xls','15')))


Agropecuária  ...  Administração, defesa, saúde e educação públicas e seguridade social
Agropecuária                                                True  ...                                               True                   
Indústrias extrativas                                       True  ...                                               True                   
Indústrias de transformação                                 True  ...                                               True                   
Eletricidade e gás, água, esgoto e gestão de re...          True  ...                                               True                   
Construção                                                  True  ...                                               True                   
Comércio                                                    True  ...                                               True                   
Transporte, armazenagem e correio                           True  ...                                               True                   
Informação e comunicação                                    True  ...                                               True                   
Atividades financeiras, de seguros e serviços r...          True  ...                                               True                   
Atividades imobiliárias                                     True  ...                                               True                   
Outras atividades de serviços                               True  ...                                               True                   
Administração, defesa, saúde e educação pública...          True  ...                                               True                   

[12 rows x 12 columns]

##Extra
---


In [ ]:
#Leontief a partir do arquivo com 20 setores do IBGE
Leontief_excel('Matriz_de_Insumo_Produto_2015_Nivel_20.xls','14')

Agricultura, pecuária, produção florestal, pesca e aquicultura  ...  Serviços domésticos
Agricultura, pecuária, produção florestal, pesc...                                           1.070176               ...                  0.0
Indústrias extrativas                                                                        0.017212               ...                  0.0
Indústrias de transformação                                                                  0.337249               ...                  0.0
Eletricidade e gás                                                                           0.047277               ...                  0.0
Água, esgoto, atividades de gestão de resíduos ...                                           0.001943               ...                  0.0
Construção                                                                                   0.002327               ...                  0.0
Comércio; reparação de veículos automotores e m...                                           0.098308               ...                  0.0
Transporte, armazenagem e correio                                                            0.053119               ...                  0.0
Alojamento e alimentação                                                                     0.001447               ...                  0.0
Informação e comunicação                                                                     0.010111               ...                  0.0
Atividades financeiras, de seguros e serviços r...                                           0.032962               ...                  0.0
Atividades imobiliárias                                                                      0.005701               ...                  0.0
Atividades científicas, profissionais e técnicas                                             0.023795               ...                  0.0
Atividades administrativas e serviços complemen...                                           0.013087               ...                  0.0
Administração pública, defesa e seguridade social                                            0.003010               ...                  0.0
Educação                                                                                     0.002117               ...                  0.0
Saúde humana e serviços sociais                                                              0.000138               ...                  0.0
Artes, cultura, esporte e recreação                                                          0.000286               ...                  0.0
Outras atividades de serviços                                                                0.001829               ...                  0.0
Serviços domésticos                                                                          0.000000               ...                  1.0

[20 rows x 20 columns]

In [ ]:
#Comparando com o leontief dado no IBGE em 20 setores
(Leontief_excel('Matriz_de_Insumo_Produto_2015_Nivel_20.xls','14') - Tratamento_excel('Matriz_de_Insumo_Produto_2015_Nivel_20.xls','15'))

Agricultura, pecuária, produção florestal, pesca e aquicultura  ...  Serviços domésticos
Agricultura, pecuária, produção florestal, pesc...                                      -2.220446e-16               ...                  0.0
Indústrias extrativas                                                                   -3.469447e-18               ...                  0.0
Indústrias de transformação                                                             -5.551115e-17               ...                  0.0
Eletricidade e gás                                                                       6.938894e-18               ...                  0.0
Água, esgoto, atividades de gestão de resíduos ...                                       0.000000e+00               ...                  0.0
Construção                                                                              -4.336809e-19               ...                  0.0
Comércio; reparação de veículos automotores e m...                                      -2.775558e-17               ...                  0.0
Transporte, armazenagem e correio                                                       -1.387779e-17               ...                  0.0
Alojamento e alimentação                                                                 0.000000e+00               ...                  0.0
Informação e comunicação                                                                 0.000000e+00               ...                  0.0
Atividades financeiras, de seguros e serviços r...                                       0.000000e+00               ...                  0.0
Atividades imobiliárias                                                                 -8.673617e-19               ...                  0.0
Atividades científicas, profissionais e técnicas                                         6.938894e-18               ...                  0.0
Atividades administrativas e serviços complemen...                                      -1.734723e-18               ...                  0.0
Administração pública, defesa e seguridade social                                       -1.734723e-18               ...                  0.0
Educação                                                                                 0.000000e+00               ...                  0.0
Saúde humana e serviços sociais                                                          0.000000e+00               ...                  0.0
Artes, cultura, esporte e recreação                                                     -1.084202e-19               ...                  0.0
Outras atividades de serviços                                                            2.168404e-19               ...                  0.0
Serviços domésticos                                                                      0.000000e+00               ...                  0.0

[20 rows x 20 columns]

In [ ]:
#Comparando os valores do modelo com o dado no site do IBGE 67 setores
#aba 14 (consumo), aba 15 (Leontief)
display(round(Leontief_excel('Matriz_de_Insumo_Produto_2015_Nivel_67.xls','14')) == round(Tratamento_excel('Matriz_de_Insumo_Produto_2015_Nivel_67.xls','15')))

Agricultura, inclusive o apoio à agricultura e a pós-colheita  ...  Serviços domésticos
Agricultura, inclusive o apoio à agricultura e ...                                               True              ...                 True
Pecuária, inclusive o apoio à pecuária                                                           True              ...                 True
Produção florestal; pesca e aquicultura                                                          True              ...                 True
Extração de carvão mineral e de minerais não me...                                               True              ...                 True
Extração de petróleo e gás, inclusive as ativid...                                               True              ...                 True
...                                                                                               ...              ...                  ...
Saúde pública                                                                                    True              ...                 True
Saúde privada                                                                                    True              ...                 True
Atividades artísticas, criativas e de espetáculos                                                True              ...                 True
Organizações associativas e outros serviços pes...                                               True              ...                 True
Serviços domésticos                                                                              True              ...                 True

[67 rows x 67 columns]

In [ ]:
#Comparando os valores do modelo com o dado no site do IBGE 67 setores
#aba 14 (consumo), aba 15 (Leontief)
df1 = round(Leontief_excel('Matriz_de_Insumo_Produto_2015_Nivel_67.xls','14')) 
df2 = round(Tratamento_excel('Matriz_de_Insumo_Produto_2015_Nivel_67.xls','15'))
print(df1.equals(df2))

True
